server:
  port: 8082

sanjy-client:
  logging:
    level: ${SANJY_CLIENT_TELEGRAM_LOGGING_LEVEL}
    file-path: ${SANJY_CLIENT_TELEGRAM_LOGGING_FILE_PATH}
    appender: ${SANJY_CLIENT_TELEGRAM_LOGGING_APPENDER}
  external-apis:
    sanjy-server:
      url: ${SANJY_CLIENT_EXTERNAL_API_SANJY_SERVER_URL}
  application:
    channel: telegram

spring:
  application:
    name: sanjy-client-telegram
  main:
    banner-mode: off
