server:
  port: 8081

sanjy-client:
  logging:
    level: ${SANJY_CLIENT_WEB_LOGGING_LEVEL}
    file-path: ${SANJY_CLIENT_WEB_LOGGING_FILE_PATH:}
    appender: ${SANJY_CLIENT_WEB_LOGGING_APPENDER}
  external-apis:
    sanjy-server:
      url: ${SANJY_CLIENT_EXTERNAL_API_SANJY_SERVER_URL}
  application:
    channel: web

spring:
  application:
    name: sanjy-client-web

  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${SANJY_CLIENT_OPENAI_API_KEY}
      organization-id: ${SANJY_CLIENT_OPENAI_ORGANIZATION_ID}
      project-id: ${SANJY_CLIENT_OPENAI_PROJECT_ID}
  main:
    banner-mode: off
